### ISSUE TITLE
Failure on Mac M1 ARM

### ISSUE THREAD

**Issue by khmarbaise** [alajmo/mani#20]
Unfortunately I get a panic like this:
```
| Cloningfatal error: concurrent map writes

goroutine 86 [running]:
runtime.throw(0x1043f78e4, 0x15)
	/opt/hostedtoolcache/go/1.16.10/x64/src/runtime/panic.go:1117 +0x54 fp=0x140002b3d40 sp=0x140002b3d10 pc=0x104239734
runtime.mapassign_faststr(0x10447d160, 0x140000b2000, 0x140000146d8, 0x18, 0x0)
	/opt/hostedtoolcache/go/1.16.10/x64/src/runtime/map_faststr.go:211 +0x3c0 fp=0x140002b3db0 sp=0x140002b3d40 pc=0x104219c70
github.com/alajmo/mani/core/dao.CloneRepo(0x1400001a060, 0x21, 0x140000146d8, 0x18, 0x140001c6800, 0x38, 0x0, 0x0, 0x14000198940, 0x40, ...)
	/home/runner/work/mani/mani/core/dao/project.go:194 +0x4b0 fp=0x140002b3f20 sp=0x140002b3db0 pc=0x1043d9fd0
runtime.goexit()
	/opt/hostedtoolcache/go/1.16.10/x64/src/runtime/asm_arm64.s:1130 +0x4 fp=0x140002b3f20 sp=0x140002b3f20 pc=0x10426bd14
created by github.com/alajmo/mani/core/dao.Config.CloneRepos
	/home/runner/work/mani/mani/core/dao/project.go:111 +0x808

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0x1400008e258)
	/opt/hostedtoolcache/go/1.16.10/x64/src/runtime/sema.go:56 +0x38
sync.(*WaitGroup).Wait(0x1400008e250)
	/opt/hostedtoolcache/go/1.16.10/x64/src/sync/waitgroup.go:130 +0x74
github.com/alajmo/mani/core/dao.Config.CloneRepos(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x140001c3590, 0x1, 0x1, 0x140001da000, ...)
	/home/runner/work/mani/mani/core/dao/project.go:122 +0x190
github.com/alajmo/mani/core/dao.Config.SyncProjects(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x140001c3590, 0x1, 0x1, 0x140001da000, ...)
	/home/runner/work/mani/mani/core/dao/config.go:566 +0x214
github.com/alajmo/mani/cmd.runSync(0x1046194a0, 0x1)
	/home/runner/work/mani/mani/cmd/sync.go:36 +0xdc

````

while running `mani sync` on a Mac M1 ARM based machine

Installed via brew.

**Additional context**
Mani version:
```
$ mani version
Version:    0.10.0
Commit:     af8f8a0e98f0a3eed64ed616357a482dd6eb7fd2
Date:       2021-11-10T10:12:45Z
```

```
$ file /opt/homebrew/bin/mani 
/opt/homebrew/bin/mani: Mach-O 64-bit executable arm64
```
If you need more details please ping me... I appreciate to. help...

**Comment by alajmo** [comment]
Thanks for bug report, I think I found the issue and was able to replicate the bug, but in the meantime, you could try `mani sync --parallel=false`.

**Comment by alajmo** [comment]
I released a new version that should hopefully resolve the concurrent map write issue, please let me know if the issue persists. 

One note though, if you're running `mani sync`, by default it will clone the repositories in parallel and lock the terminal screen so if you need to enter credentials manually, it's better to run with `mani sync --parallel=false` since it won't lock the screen.

**Comment by khmarbaise** [comment]
I can confirm that the above panic does not occurs anymore.
